### ISSUE TITLE
separated_parenthesis fails with nesting

### ISSUE THREAD

**Issue by thoppe** [NIHOPA/NLPre#62]
``` python
from nlpre import separated_parenthesis
text = ('''Superoxide anion (A[B?])''')
print separated_parenthesis()(text)
```

```
Traceback (most recent call last):
  File "tx.py", line 11, in <module>
    print separated_parenthesis()(text)
  File "/usr/local/lib/python2.7/dist-packages/nlpre/separated_parenthesis.py", line 68, in __call__
    tokens = self.grammar.grammar.parseString(sent)
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1617, in parseString
    raise exc
pyparsing.ParseException: Expected {W:(0123...) | nested () expression | nested [] expression | nested {} expression} (at char 0), (line:1, col:1)
```

**Comment by HarryBaker** [comment]
This is an interesting edge case. It fails because there's punctuation within the parenthetical content AND because there is nesting with mixed parenthesis. This feeds a sentence with an unfinished parenthesis into the pyparsing grammar class (It enters 'Superoxide anion (A[B ?'). This then throws an error, because pyparsing doesn't like it when mixed parenthesis are entered. Interestingly, this doesn't happen when you use text = ('''Superoxide anion (A(B?))''') .

You can prevent errors like this by moving the pyparsing function into the else statement, so it only triggers when a sentence doesn't have unbalanced parenthesis.

**Comment by thoppe** [comment]
It looks like this isn't complete. Here is another real world example that caused it to fail.

``` python
from nlpre import separated_parenthesis as parser
text = "Low-activity state ([?]19 DIV) followed by ([?]20 DIV)"
print parser()(text)
```

with 

```
Traceback (most recent call last):
  File "tx.py", line 15, in <module>
    print parser()(text)
  File "/home/hoppeta/git-repo/NLPre/nlpre/separated_parenthesis.py", line 89, in __call__
    tokens = self.grammar.grammar.parseString(sent)
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1617, in parseString
    raise exc
pyparsing.ParseException: Expected {W:(0123...) | nested () expression | nested [] expression | nested {} expression} (at char 0), (line:1, col:1)
```
