### ISSUE TITLE
Possessive tags not being handled correctly

### ISSUE THREAD

**Issue by thoppe** [NIHOPA/NLPre#63]
This is probably due to them being stripped out in the pipeline before. This should be an easy fix as we just need to add `POS` to the list of tags. 

``` python
from nlpre import pos_tokenizer as parser
text = ("fins's")
print parser([])(text)
```

```
Traceback (most recent call last):
  File "tx.py", line 12, in <module>
    print parser(blacklist)(text)
  File "/usr/local/lib/python2.7/dist-packages/nlpre/pos_tokenizer.py", line 113, in __call__
    pos = self.POS_map[tag]
KeyError: u'POS'
```

**Comment by thoppe** [comment]
Still missing some POS tags, here is a failing block

``` python

from nlpre import pos_tokenizer as parser
text = '''
Would such a shared expression pattern be sufficient to infer homology between fish fins and mouse limbs? We investigated this question here, looking at whether the two phases of Hox gene transcription that are observed during tetrapod limb development also occur during zebrafish fin development. For although the mechanisms that regulate the expression of Hoxa and Hoxd are comparable between zebrafish fins and mouse limbs, when the genomic regions that regulate Hox gene expression in fish fins are introduced into transgenic mice, they trigger Hox gene expression in only the proximal limb segment (the segment nearest the body) and not in the presumptive digits. We conclude that although fish have the Hox regulatory toolkit to produce digits, this potential is not utilized as it is in tetrapods, and as a result we propose that fin radials--the bony elements of fins--are not homologous to tetrapod digits.
'''
P = parser([])
print P(text)
```
